=begin
#PACE Funding API

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0
Contact: 
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module PaceFunding

  class CustomerDetail
    attr_accessor :project_id

    attr_accessor :property_type

    attr_accessor :property_ownership

    attr_accessor :property_ownership_name

    attr_accessor :fo_first_name

    attr_accessor :fo_last_name

    attr_accessor :fo_suffix

    attr_accessor :fo_phone

    attr_accessor :fo_email

    attr_accessor :fo_same_as

    attr_accessor :fo_address

    attr_accessor :fo_unit

    attr_accessor :fo_city

    attr_accessor :fo_state

    attr_accessor :fo_zipcode

    attr_accessor :so_first_name

    attr_accessor :so_last_name

    attr_accessor :so_suffix

    attr_accessor :so_phone

    attr_accessor :so_email

    attr_accessor :so_same_as

    attr_accessor :so_address

    attr_accessor :so_unit

    attr_accessor :so_city

    attr_accessor :so_state

    attr_accessor :so_zipcode


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'project_id' => :'projectId',
        :'property_type' => :'property_type',
        :'property_ownership' => :'property_ownership',
        :'property_ownership_name' => :'property_ownership_name',
        :'fo_first_name' => :'fo_first_name',
        :'fo_last_name' => :'fo_last_name',
        :'fo_suffix' => :'fo_suffix',
        :'fo_phone' => :'fo_phone',
        :'fo_email' => :'fo_email',
        :'fo_same_as' => :'fo_same_as',
        :'fo_address' => :'fo_address',
        :'fo_unit' => :'fo_unit',
        :'fo_city' => :'fo_city',
        :'fo_state' => :'fo_state',
        :'fo_zipcode' => :'fo_zipcode',
        :'so_first_name' => :'so_first_name',
        :'so_last_name' => :'so_last_name',
        :'so_suffix' => :'so_suffix',
        :'so_phone' => :'so_phone',
        :'so_email' => :'so_email',
        :'so_same_as' => :'so_same_as',
        :'so_address' => :'so_address',
        :'so_unit' => :'so_unit',
        :'so_city' => :'so_city',
        :'so_state' => :'so_state',
        :'so_zipcode' => :'so_zipcode'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'project_id' => :'String',
        :'property_type' => :'String',
        :'property_ownership' => :'String',
        :'property_ownership_name' => :'String',
        :'fo_first_name' => :'String',
        :'fo_last_name' => :'String',
        :'fo_suffix' => :'String',
        :'fo_phone' => :'String',
        :'fo_email' => :'String',
        :'fo_same_as' => :'String',
        :'fo_address' => :'String',
        :'fo_unit' => :'String',
        :'fo_city' => :'String',
        :'fo_state' => :'String',
        :'fo_zipcode' => :'String',
        :'so_first_name' => :'String',
        :'so_last_name' => :'String',
        :'so_suffix' => :'String',
        :'so_phone' => :'String',
        :'so_email' => :'String',
        :'so_same_as' => :'String',
        :'so_address' => :'String',
        :'so_unit' => :'String',
        :'so_city' => :'String',
        :'so_state' => :'String',
        :'so_zipcode' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'projectId')
        self.project_id = attributes[:'projectId']
      else
        self.project_id = ""
      end

      if attributes.has_key?(:'property_type')
        self.property_type = attributes[:'property_type']
      else
        self.property_type = ""
      end

      if attributes.has_key?(:'property_ownership')
        self.property_ownership = attributes[:'property_ownership']
      else
        self.property_ownership = ""
      end

      if attributes.has_key?(:'property_ownership_name')
        self.property_ownership_name = attributes[:'property_ownership_name']
      else
        self.property_ownership_name = ""
      end

      if attributes.has_key?(:'fo_first_name')
        self.fo_first_name = attributes[:'fo_first_name']
      else
        self.fo_first_name = ""
      end

      if attributes.has_key?(:'fo_last_name')
        self.fo_last_name = attributes[:'fo_last_name']
      else
        self.fo_last_name = ""
      end

      if attributes.has_key?(:'fo_suffix')
        self.fo_suffix = attributes[:'fo_suffix']
      else
        self.fo_suffix = ""
      end

      if attributes.has_key?(:'fo_phone')
        self.fo_phone = attributes[:'fo_phone']
      else
        self.fo_phone = ""
      end

      if attributes.has_key?(:'fo_email')
        self.fo_email = attributes[:'fo_email']
      else
        self.fo_email = ""
      end

      if attributes.has_key?(:'fo_same_as')
        self.fo_same_as = attributes[:'fo_same_as']
      else
        self.fo_same_as = ""
      end

      if attributes.has_key?(:'fo_address')
        self.fo_address = attributes[:'fo_address']
      else
        self.fo_address = ""
      end

      if attributes.has_key?(:'fo_unit')
        self.fo_unit = attributes[:'fo_unit']
      else
        self.fo_unit = ""
      end

      if attributes.has_key?(:'fo_city')
        self.fo_city = attributes[:'fo_city']
      else
        self.fo_city = ""
      end

      if attributes.has_key?(:'fo_state')
        self.fo_state = attributes[:'fo_state']
      else
        self.fo_state = ""
      end

      if attributes.has_key?(:'fo_zipcode')
        self.fo_zipcode = attributes[:'fo_zipcode']
      else
        self.fo_zipcode = ""
      end

      if attributes.has_key?(:'so_first_name')
        self.so_first_name = attributes[:'so_first_name']
      else
        self.so_first_name = ""
      end

      if attributes.has_key?(:'so_last_name')
        self.so_last_name = attributes[:'so_last_name']
      else
        self.so_last_name = ""
      end

      if attributes.has_key?(:'so_suffix')
        self.so_suffix = attributes[:'so_suffix']
      else
        self.so_suffix = ""
      end

      if attributes.has_key?(:'so_phone')
        self.so_phone = attributes[:'so_phone']
      else
        self.so_phone = ""
      end

      if attributes.has_key?(:'so_email')
        self.so_email = attributes[:'so_email']
      else
        self.so_email = ""
      end

      if attributes.has_key?(:'so_same_as')
        self.so_same_as = attributes[:'so_same_as']
      else
        self.so_same_as = ""
      end

      if attributes.has_key?(:'so_address')
        self.so_address = attributes[:'so_address']
      else
        self.so_address = ""
      end

      if attributes.has_key?(:'so_unit')
        self.so_unit = attributes[:'so_unit']
      else
        self.so_unit = ""
      end

      if attributes.has_key?(:'so_city')
        self.so_city = attributes[:'so_city']
      else
        self.so_city = ""
      end

      if attributes.has_key?(:'so_state')
        self.so_state = attributes[:'so_state']
      else
        self.so_state = ""
      end

      if attributes.has_key?(:'so_zipcode')
        self.so_zipcode = attributes[:'so_zipcode']
      else
        self.so_zipcode = ""
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          project_id == o.project_id &&
          property_type == o.property_type &&
          property_ownership == o.property_ownership &&
          property_ownership_name == o.property_ownership_name &&
          fo_first_name == o.fo_first_name &&
          fo_last_name == o.fo_last_name &&
          fo_suffix == o.fo_suffix &&
          fo_phone == o.fo_phone &&
          fo_email == o.fo_email &&
          fo_same_as == o.fo_same_as &&
          fo_address == o.fo_address &&
          fo_unit == o.fo_unit &&
          fo_city == o.fo_city &&
          fo_state == o.fo_state &&
          fo_zipcode == o.fo_zipcode &&
          so_first_name == o.so_first_name &&
          so_last_name == o.so_last_name &&
          so_suffix == o.so_suffix &&
          so_phone == o.so_phone &&
          so_email == o.so_email &&
          so_same_as == o.so_same_as &&
          so_address == o.so_address &&
          so_unit == o.so_unit &&
          so_city == o.so_city &&
          so_state == o.so_state &&
          so_zipcode == o.so_zipcode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [project_id, property_type, property_ownership, property_ownership_name, fo_first_name, fo_last_name, fo_suffix, fo_phone, fo_email, fo_same_as, fo_address, fo_unit, fo_city, fo_state, fo_zipcode, so_first_name, so_last_name, so_suffix, so_phone, so_email, so_same_as, so_address, so_unit, so_city, so_state, so_zipcode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = PaceFunding.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
