=begin
#PACE Funding API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0
Contact: 
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for PaceFunding::06CreateContractorSalespersonApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe '06CreateContractorSalespersonApi' do
  before do
    # run before each test
    @instance = PaceFunding::06CreateContractorSalespersonApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of 06CreateContractorSalespersonApi' do
    it 'should create an instact of 06CreateContractorSalespersonApi' do
      expect(@instance).to be_instance_of(PaceFunding::06CreateContractorSalespersonApi)
    end
  end

  # unit tests for add_contractor_post
  #  
  # 
  # @param auth_key Auth Key
  # @param title Contractor title
  # @param first_name Contractor first name
  # @param last_name Contractor last name
  # @param phone Contractor Work number
  # @param mobile Contractor Mobile Number
  # @param email Contractor Email id
  # @param probationary Contractor probationary 1&#x3D;Yes or 0&#x3D;No
  # @param company_name Contractor company name
  # @param website Company website
  # @param company_phone Company phone number
  # @param license_number License number
  # @param license_state License state
  # @param license_expiration License Expiration Date MM/DD/YYYY
  # @param company_address Company Address Line 1
  # @param company_city Company City
  # @param company_state Company State
  # @param company_pincode Company Pincode
  # @param project_type Project Type
  # @param administrator_name Administrator/Executive Contact Name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :company_address2 Company Address Line 2
  # @return [nil]
  describe 'add_contractor_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for add_salesperson_post
  #  
  # 
  # @param auth_key Auth Key
  # @param contractor_code Contractor Code
  # @param title Sales person title
  # @param first_name Sales person first name
  # @param last_name Sales person last name
  # @param phone Sales person Work number
  # @param mobile Sales person Mobile Number
  # @param email Sales person Email id
  # @param address1 Sales person Address Line 1
  # @param city Sales person city name
  # @param state Sales person State
  # @param probationary Sales person probationary 1&#x3D;Yes or 0&#x3D;No
  # @param [Hash] opts the optional parameters
  # @option opts [String] :address2 Sales person Address Line 2
  # @return [nil]
  describe 'add_salesperson_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
