=begin
#PACE Funding API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0
Contact: 
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for PaceFunding::09PostProjectCancellationFormApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe '09PostProjectCancellationFormApi' do
  before do
    # run before each test
    @instance = PaceFunding::09PostProjectCancellationFormApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of 09PostProjectCancellationFormApi' do
    it 'should create an instact of 09PostProjectCancellationFormApi' do
      expect(@instance).to be_instance_of(PaceFunding::09PostProjectCancellationFormApi)
    end
  end

  # unit tests for post_project_cancellation_post
  # Post Project Cancellation Form
  # Post Project Cancellation Form
  # @param auth_key Auth Key
  # @param contractor_code Contractor Code
  # @param salesperson_code Salesperson Code
  # @param project_id Project Id
  # @param file base64 encoded file
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_project_cancellation_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
