=begin
#PACE Funding API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0
Contact: 
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for PaceFunding::10SendCompletionCertificateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe '10SendCompletionCertificateApi' do
  before do
    # run before each test
    @instance = PaceFunding::10SendCompletionCertificateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of 10SendCompletionCertificateApi' do
    it 'should create an instact of 10SendCompletionCertificateApi' do
      expect(@instance).to be_instance_of(PaceFunding::10SendCompletionCertificateApi)
    end
  end

  # unit tests for send_completion_certificate_post
  # Send Completion Certificate
  # Send Completion Certificate
  # @param auth_key Auth Key
  # @param contractor_code Contractor Code
  # @param salesperson_code Salesperson Code
  # @param project_id Project Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fo_client_id First Property Owner client user id for docusign embedded signing. 
  # @option opts [String] :so_client_id Second Property Owner client user id for docusign embedded signing. 
  # @option opts [String] :co_client_id Contractor client user id for docusign embedded signing
  # @return [nil]
  describe 'send_completion_certificate_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
