=begin
#PACE Funding API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0
Contact: 
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require "uri"

module PaceFunding
  class 01AddressEligibilityApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Check address eligibility.
    # 
    # @param auth_key Auth Key
    # @param contractor_code Contractor Code
    # @param salesperson_code Salesperson Code
    # @param address Eligible Address
    # @param zipcode Zipcode
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def check_address_eligibility_post(auth_key, contractor_code, salesperson_code, address, zipcode, opts = {})
      check_address_eligibility_post_with_http_info(auth_key, contractor_code, salesperson_code, address, zipcode, opts)
      return nil
    end

    # Check address eligibility.
    # 
    # @param auth_key Auth Key
    # @param contractor_code Contractor Code
    # @param salesperson_code Salesperson Code
    # @param address Eligible Address
    # @param zipcode Zipcode
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def check_address_eligibility_post_with_http_info(auth_key, contractor_code, salesperson_code, address, zipcode, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: 01AddressEligibilityApi.check_address_eligibility_post ..."
      end
      # verify the required parameter 'auth_key' is set
      fail ArgumentError, "Missing the required parameter 'auth_key' when calling 01AddressEligibilityApi.check_address_eligibility_post" if auth_key.nil?
      # verify the required parameter 'contractor_code' is set
      fail ArgumentError, "Missing the required parameter 'contractor_code' when calling 01AddressEligibilityApi.check_address_eligibility_post" if contractor_code.nil?
      # verify the required parameter 'salesperson_code' is set
      fail ArgumentError, "Missing the required parameter 'salesperson_code' when calling 01AddressEligibilityApi.check_address_eligibility_post" if salesperson_code.nil?
      # verify the required parameter 'address' is set
      fail ArgumentError, "Missing the required parameter 'address' when calling 01AddressEligibilityApi.check_address_eligibility_post" if address.nil?
      if address.to_s.length > 63
        fail ArgumentError, 'invalid value for "address" when calling 01AddressEligibilityApi.check_address_eligibility_post, the character length must be smaller than or equal to 63.'
      end

      # verify the required parameter 'zipcode' is set
      fail ArgumentError, "Missing the required parameter 'zipcode' when calling 01AddressEligibilityApi.check_address_eligibility_post" if zipcode.nil?
      # resource path
      local_var_path = "/check-address-eligibility".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/xml', 'application/json']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/x-www-form-urlencoded']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}
      form_params["auth_key"] = auth_key
      form_params["contractor_code"] = contractor_code
      form_params["salesperson_code"] = salesperson_code
      form_params["address"] = address
      form_params["zipcode"] = zipcode

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: 01AddressEligibilityApi#check_address_eligibility_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
