=begin
#PACE Funding API

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0
Contact: 
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require "uri"

module PaceFunding
  class CreditApplicationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Send Credit Application 
    # Send Credit Application 
    # @param auth_key Auth Key
    # @param contractor_code Contractor Code
    # @param salesperson_code Salesperson Code
    # @param project_id Project Id
    # @param notify_url PACE Funding send the credit decision on notify url
    # @param email_address Email Address
    # @param owner_first_name Owner first Name
    # @param owner_last_name Owner Last Name
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def send_credit_application_post(auth_key, contractor_code, salesperson_code, project_id, notify_url, email_address, owner_first_name, owner_last_name, opts = {})
      send_credit_application_post_with_http_info(auth_key, contractor_code, salesperson_code, project_id, notify_url, email_address, owner_first_name, owner_last_name, opts)
      return nil
    end

    # Send Credit Application 
    # Send Credit Application 
    # @param auth_key Auth Key
    # @param contractor_code Contractor Code
    # @param salesperson_code Salesperson Code
    # @param project_id Project Id
    # @param notify_url PACE Funding send the credit decision on notify url
    # @param email_address Email Address
    # @param owner_first_name Owner first Name
    # @param owner_last_name Owner Last Name
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def send_credit_application_post_with_http_info(auth_key, contractor_code, salesperson_code, project_id, notify_url, email_address, owner_first_name, owner_last_name, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: CreditApplicationApi.send_credit_application_post ..."
      end
      # verify the required parameter 'auth_key' is set
      fail ArgumentError, "Missing the required parameter 'auth_key' when calling CreditApplicationApi.send_credit_application_post" if auth_key.nil?
      # verify the required parameter 'contractor_code' is set
      fail ArgumentError, "Missing the required parameter 'contractor_code' when calling CreditApplicationApi.send_credit_application_post" if contractor_code.nil?
      # verify the required parameter 'salesperson_code' is set
      fail ArgumentError, "Missing the required parameter 'salesperson_code' when calling CreditApplicationApi.send_credit_application_post" if salesperson_code.nil?
      # verify the required parameter 'project_id' is set
      fail ArgumentError, "Missing the required parameter 'project_id' when calling CreditApplicationApi.send_credit_application_post" if project_id.nil?
      # verify the required parameter 'notify_url' is set
      fail ArgumentError, "Missing the required parameter 'notify_url' when calling CreditApplicationApi.send_credit_application_post" if notify_url.nil?
      # verify the required parameter 'email_address' is set
      fail ArgumentError, "Missing the required parameter 'email_address' when calling CreditApplicationApi.send_credit_application_post" if email_address.nil?
      # verify the required parameter 'owner_first_name' is set
      fail ArgumentError, "Missing the required parameter 'owner_first_name' when calling CreditApplicationApi.send_credit_application_post" if owner_first_name.nil?
      # verify the required parameter 'owner_last_name' is set
      fail ArgumentError, "Missing the required parameter 'owner_last_name' when calling CreditApplicationApi.send_credit_application_post" if owner_last_name.nil?
      # resource path
      local_var_path = "/send-credit-application".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/xml', 'application/json']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/x-www-form-urlencoded']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}
      form_params["auth_key"] = auth_key
      form_params["contractor_code"] = contractor_code
      form_params["salesperson_code"] = salesperson_code
      form_params["projectId"] = project_id
      form_params["notify_url"] = notify_url
      form_params["email_address"] = email_address
      form_params["owner_first_name"] = owner_first_name
      form_params["owner_last_name"] = owner_last_name

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CreditApplicationApi#send_credit_application_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
